version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: cart-webserver
    working_dir: /app
    volumes:
      - ./../:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "8889:80"
  php:
    build: ./php
#    links:
#      - mysql
    volumes:
      - ./../:/app